import shutil
from random import randint

#---------__------VARIABLES_-----------------------------
# Specifying the folder to delete
folderName = r"C:\Users\Acer\Desktop\Python_Beep\DemoFolder"

# Generating a random number between 1 to 10 including both limits
randomNumber = randint(1,10)
# Specifying the chances
chances = 3


#-------------------INFO TO USER----------------------
print("--------RUSSIAN ROULETTE IN PC--------\n")

print("A random number is generated by the PC.\nGuess the number correctly to save the folder.")
print(f"Target Folder: {folderName} \n")

print("The range for the number to be guessed is 1 to 10.")
print("You have 3 chances to guess the correct number.\n")


while(chances > 0):
    userGuess = int(input("Enter you guess: "))

    if(userGuess == randomNumber):
        print("*** CONGRATULATIONS!! You Saved Your Folder  ***")
        break
    else:
        chances -= 1
        print(f"BOOO..BOO...Wrong Guess!! You have {chances} chances left.\n")
    

if chances==0:
    print("---You FUCKED UP----\nHAHAHAHAHA----")
    try:
        shutil.rmtree(folderName)
        print(f"Folder at location {folderName} deleted successfuly.")
    except OSError as x:
        print(f"Could not delete:  {folderName}")